/// Flutter icons BootstrapItaliaIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BootstrapItaliaIcons
///      fonts:
///       - asset: fonts/BootstrapItaliaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BootstrapItaliaIcons {
  BootstrapItaliaIcons._();

  static const _kFontFam = 'BootstrapItaliaIcons';
  static const String? _kFontPkg = 'bootstrap_italia_icons';

  static const IconData it_android = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_android_square = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_apple = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_apple_square = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_down = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_down_circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_down_triangle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_left = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_left_circle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_left_triangle = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_right = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_right_circle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_right_triangle = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_up = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_up_circle = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_arrow_up_triangle = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_ban = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_behance = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_bluesky = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_bookmark = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_burger = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_calendar = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_camera = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_car = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_card = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_cart = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_chart_line = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_check = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_check_circle = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_chevron_left = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_chevron_right = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_clip = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_clock = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_close = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_close_big = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_close_circle = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_code_circle = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_collapse = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_comment = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_copy = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_delete = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_designers_italia = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_download = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_error = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_exchange_circle = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_expand = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_external_link = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_facebook = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_facebook_square = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_figma = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_figma_square = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_audio = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_compressed = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_csv = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_docx = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_image = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_json = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_odp = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_ods = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_odt = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_pdf = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_pdf_ext = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_ppt = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_files = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_sheet = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_signed = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_slides = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_txt = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_video = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_xlsx = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_file_xml = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_flag = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_flickr = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_flickr_square = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_folder = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_fullscreen = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_funnel = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_github = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_google = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_hearing = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_help = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_help_circle = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_horn = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_info_circle = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_instagram = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_key = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_less_circle = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_link = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_linkedin = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_linkedin_square = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_list = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_lock = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_locked = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_logout = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_mail = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_mail_open = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_map_marker = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_map_marker_circle = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_mastodon = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_mastodon_square = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_maximize = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_maximize_alt = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_medium = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_medium_square = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_minimize = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_minus = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_minus_circle = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_moodle = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_moodle_square = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_more_actions = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_more_items = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_note = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_open_source = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_pa = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_password_invisible = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_password_visible = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_pencil = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_piattaforme = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_pin = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_pinterest = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_pinterest_square = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_plug = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_plus = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_plus_circle = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_presentation = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_print = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_quora = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_quora_square = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_reddit = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_reddit_square = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_refresh = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_restore = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_rss = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_rss_square = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_search = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_settings = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_share = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_sign = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_slack = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_slack_square = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_snapchat = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_snapchat_square = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_software = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_spotify = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_stackexchange = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_stackexchange_square = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_stackoverflow = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_stackoverflow_square = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_star_full = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_star_outline = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_team_digitale = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_telegram = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_telephone = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_threads = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_threads_square = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_tiktok = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_tiktok_square = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_tool = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_twitter = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_twitter_square = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_unlocked = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_upload = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_user = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_video = IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_vimeo = IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_vimeo_square = IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_warning = IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_warning_circle = IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_whatsapp = IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_whatsapp_square = IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_wifi = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_youtube = IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_zoom_in = IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_zoom_out = IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_box = IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_map_marker_plus = IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_inbox = IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData it_map_marker_minus = IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
